# Alacritty Configuration
# env:
#   TERM: xterm-256color

alt_send_esc: false
live_config_reload: true
debug:
  render_timer: false
  persistent_logging: false
  log_level: Debug
  print_events: false
  ref_test: false
  print_events: false
  ref_test: false

window:
  dimensions:
    columns: 150
    lines: 70
  padding:
    x: 0
    y: 0
  dynamic_padding: false

scrolling:
  history: 10000

decorations: full

fam: &fam "Edlo" # "JetBrains Mono"

font:
  size: 14
  normal:
    family: *fam
    style: "Regular"
  bold:
    family: *fam
    style: "Bold"
  italic:
    family: *fam
    style: "Italic"
  bold_italic:
    family: *fam
    style: "Bold Italic"

use_thin_strokes: true
draw_bold_text_with_bright_colors: true

theme: &zenburn-tinker
  name: zenburntinker
  primary:
    background: '#3f3f3f'
    foreground: '#dcdccc'
  cursor:
    text: '#000d18'
    cursor: '#8faf9f'
  normal:
    black: "#1f1f1f"
    red: "#cc9393"
    green: "#5f7f5f"
    yellow: "#dfaf8f"
    blue: "#8cb0d3"
    magenta: "#dc8cc3"
    cyan: "#71d3b4"
    white: "#dfe4cf"

colors: *zenburn-tinker

bell:
  animation: EaseOutExpo
  duration: 0
  color: '#FFFFFF'

# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
custom_cursor_colors: true

unfocused_hollow: true
cursor:
  style: Block

selection:
  semantic_escape_chars: ",`|:\"'()[]{}<>\t\n"
  dynamic_title: true

mouse_bindings:
 - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 275 }
  triple_click: { threshold: 275 }
  hide_when_typing: true

# Key Bindings:
key_bindings:
  - { key: Paste, action: Paste}
  - { key: Copy, action: Copy}

