# Alacritty Configuration
env:
  TERM: xterm-256color

alt_send_esc: false
live_config_reload: true
debug:
  render_timer: false
  persistent_logging: false
  log_level: Debug
  print_events: false
  ref_test: false
  print_events: false
  ref_test: false

window:
  dimensions:
    columns: 150
    lines: 70
  padding:
    x: 0
    y: 0
  dynamic_padding: false

scrolling:
  history: 10000

decorations: full

# fam: &fam "JetBrains Mono"
fam: &fam "Monaco"
font:
  size: 12
  normal:
    family: *fam
    style: "Regular"
  bold:
    family: *fam
    style: "Bold"
  italic:
    family: *fam
    style: "Italic"
  bold_italic:
    family: *fam
    style: "Bold Italic"

use_thin_strokes: true
draw_bold_text_with_bright_colors: true

# Color theme ported from Konsole: Linux colors 
colors:  
  primary:
    foreground: '0xe3e3e3'
    bright_foreground: '0xffffff'
    dim_foreground:    '0xe3e3e3'
    background: '0x000000'
    bright_background: '0x686868' # not sure
    dim_background:    '0x1f1f1f' # not sure

  cursor:
    text: '0x191622'
    cursor: '0xf8f8f2'

  search:
    matches:
      foreground: '0xb2b2b2'
      background: '0xb26818'
    focused_match:
      foreground: CellBackground
      background: CellForeground

  normal:
    black:   '0x000000'
    red:     '0xb21818'
    green:   '0x18b218'
    yellow:  '0xb26818'
    blue:    '0x5454ff'
    magenta: '0xb218b2'
    cyan:    '0x18b2b2'
    white:   '0xb2b2b2'

  bright:
    black:   '0x686868'
    red:     '0xff5454'
    green:   '0x54ff54'
    yellow:  '0xffff54'
    blue:    '0x5454ff'
    magenta: '0xff54ff'
    cyan:    '0x54ffff'
    white:   '0xffffff'

  dim:
    black:   '0x000000'
    red:     '0xb21818'
    green:   '0x18b218'
    yellow:  '0xb26818'
    blue:    '0x1818b2'
    magenta: '0xb218b2'
    cyan:    '0x18b2b2'
    white:   '0xb2b2b2'

bell:
  animation: EaseOutExpo
  duration: 0
  color: '#FFFFFF'

# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
custom_cursor_colors: true

unfocused_hollow: true
cursor:
  style: Block

selection:
  semantic_escape_chars: ",`|:\"'()[]{}<>\t\n"
  dynamic_title: true

mouse_bindings:
 - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 275 }
  triple_click: { threshold: 275 }
  hide_when_typing: true

# Key Bindings:
key_bindings:
  - { key: Paste, action: Paste}
  - { key: Copy, action: Copy}

