# Alacritty Configuration
env:
  TERM: xterm-256color

alt_send_esc: false
live_config_reload: true
debug:
  render_timer: false
  persistent_logging: false
  log_level: Debug
  print_events: false
  ref_test: false
  print_events: false
  ref_test: false

window:
  dimensions:
    columns: 150
    lines: 70
  padding:
    x: 0
    y: 0
  dynamic_padding: false

scrolling:
  history: 10000

decorations: full

# fam: &fam "Monoid"
fam: &fam "Liberation Mono"
font:
  size: 14
  normal:
    family: *fam
    style: "Regular"
  bold:
    family: *fam
    style: "Bold"
  italic:
    family: *fam
    style: "Italic"
  bold_italic:
    family: *fam
    style: "Bold Italic"

schemes:
  # Gruvbox Vim Scheme Colors
  gruvbox: &gruvbox
    primary:
      background: '#282828'
      foreground: '#ebdbb2'
    normal:
      black:   '0x3c3836'
      red:     '#cc241d'
      green:   '#98971a'
      yellow:  '#d79921'
      blue:    '#458588'
      magenta: '#b16286'
      cyan:    '#689d6a'
      white:   '#ebdbb2'
    bright:
      black:   '#fb4934'
      red:     '0xea6962'
      green:   '#b8bb26'
      yellow:  '#fabd2f'
      blue:    '#83a598'
      magenta: '#d3869b'
      cyan:    '#8ec07c'
      white:   '#ebdbb2'

colors: *gruvbox

use_thin_strokes: true
draw_bold_text_with_bright_colors: true

bell:
  animation: EaseOutExpo
  duration: 0
  color: '#FFFFFF'

# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
custom_cursor_colors: true

unfocused_hollow: true
cursor:
  style: Block

selection:
  semantic_escape_chars: ",`|:\"'()[]{}<>\t\n"
  dynamic_title: true

mouse_bindings:
 - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 275 }
  triple_click: { threshold: 275 }
  hide_when_typing: true

# Key Bindings:
key_bindings:
  - { key: Paste, action: Paste}
  - { key: Copy, action: Copy}

